# Generated by Django 3.0 on 2020-03-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_additional_info',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
